services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: streamlit-app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    restart: unless-stopped